# Generated by Django 5.2.4 on 2025-08-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('DAILY_SALES', 'Daily Sales Report'), ('WEEKLY_SALES', 'Weekly Sales Report'), ('MONTHLY_SALES', 'Monthly Sales Report'), ('INVENTORY', 'Inventory Report'), ('PROFIT_LOSS', 'Profit & Loss Report'), ('CUSTOMER_ANALYSIS', 'Customer Analysis'), ('PRODUCT_PERFORMANCE', 'Product Performance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('DAILY_SALES', 'Daily Sales Report'), ('WEEKLY_SALES', 'Weekly Sales Report'), ('MONTHLY_SALES', 'Monthly Sales Report'), ('INVENTORY', 'Inventory Report'), ('PROFIT_LOSS', 'Profit & Loss Report'), ('CUSTOMER_ANALYSIS', 'Customer Analysis'), ('PRODUCT_PERFORMANCE', 'Product Performance')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
